import { TaskDefinition, TaskDefinitions, TaskType, MinigameType } from '../types';

export const SKELD_TASKS: TaskDefinitions = {
  mapId: 'the-skeld',
  mapName: 'The Skeld',
  tasks: [
    {
      id: 'electrical-fix-wiring',
      name: 'Fix Wiring',
      description: 'Connect the matching colored wires from left to right.',
      taskType: TaskType.SHORT,
      roomId: 'electrical',
      minigameType: MinigameType.WIRES,
      isVisual: false,
    },
    {
      id: 'electrical-calibrate-distributor',
      name: 'Calibrate Distributor',
      description: 'Align the spinning distributor to the correct position.',
      taskType: TaskType.LONG,
      roomId: 'electrical',
      minigameType: MinigameType.SWIPE,
      isVisual: false,
    },
    {
      id: 'admin-swipe-card',
      name: 'Swipe Card',
      description: 'Swipe your card at the correct speed to gain access.',
      taskType: TaskType.SHORT,
      roomId: 'admin',
      minigameType: MinigameType.SWIPE,
      isVisual: false,
    },
    {
      id: 'admin-upload-data',
      name: 'Upload Data',
      description: 'Upload data to the administrative terminal.',
      taskType: TaskType.SHORT,
      roomId: 'admin',
      minigameType: MinigameType.UPLOAD,
      isVisual: false,
    },
    {
      id: 'cafeteria-upload-data',
      name: 'Upload Data',
      description: 'Upload data from the cafeteria terminal.',
      taskType: TaskType.SHORT,
      roomId: 'cafeteria',
      minigameType: MinigameType.UPLOAD,
      isVisual: false,
    },
    {
      id: 'cafeteria-empty-garbage',
      name: 'Empty Garbage',
      description: 'Empty the garbage chute in the cafeteria.',
      taskType: TaskType.SHORT,
      roomId: 'cafeteria',
      minigameType: MinigameType.EMPTY,
      isVisual: false,
    },
    {
      id: 'weapons-clear-asteroids',
      name: 'Clear Asteroids',
      description: 'Destroy the asteroids threatening the ship.',
      taskType: TaskType.LONG,
      roomId: 'weapons',
      minigameType: MinigameType.DOWNLOAD,
      isVisual: false,
    },
    {
      id: 'weapons-upload-data',
      name: 'Upload Data',
      description: 'Upload targeting data to the weapons system.',
      taskType: TaskType.SHORT,
      roomId: 'weapons',
      minigameType: MinigameType.UPLOAD,
      isVisual: false,
    },
    {
      id: 'navigation-chart-course',
      name: 'Chart Course',
      description: 'Plot the ships course through space.',
      taskType: TaskType.LONG,
      roomId: 'navigation',
      minigameType: MinigameType.DOWNLOAD,
      isVisual: false,
    },
    {
      id: 'navigation-clear-asteroids',
      name: 'Clear Asteroids',
      description: 'Clear asteroids from the navigation path.',
      taskType: TaskType.LONG,
      roomId: 'navigation',
      minigameType: MinigameType.DOWNLOAD,
      isVisual: false,
    },
    {
      id: 'o2-clean-filter',
      name: 'Clean Filter',
      description: 'Clean the O2 filter to maintain air quality.',
      taskType: TaskType.SHORT,
      roomId: 'o2',
      minigameType: MinigameType.SWIPE,
      isVisual: false,
    },
    {
      id: 'o2-empty-garbage',
      name: 'Empty Garbage',
      description: 'Empty the garbage in the O2 section.',
      taskType: TaskType.SHORT,
      roomId: 'o2',
      minigameType: MinigameType.EMPTY,
      isVisual: false,
    },
    {
      id: 'shields-prime-shields',
      name: 'Prime Shields',
      description: 'Activate the shield systems.',
      taskType: TaskType.SHORT,
      roomId: 'shields',
      minigameType: MinigameType.SWIPE,
      isVisual: false,
    },
    {
      id: 'communications-fix-wiring',
      name: 'Fix Wiring',
      description: 'Repair the communication wiring.',
      taskType: TaskType.SHORT,
      roomId: 'communications',
      minigameType: MinigameType.WIRES,
      isVisual: false,
    },
    {
      id: 'communications-upload-data',
      name: 'Upload Data',
      description: 'Upload data to the communications array.',
      taskType: TaskType.SHORT,
      roomId: 'communications',
      minigameType: MinigameType.UPLOAD,
      isVisual: false,
    },
    {
      id: 'storage-fuel-engines',
      name: 'Fuel Engines',
      description: 'Refuel the ships engines from storage.',
      taskType: TaskType.LONG,
      roomId: 'storage',
      minigameType: MinigameType.FUEL,
      isVisual: false,
    },
    {
      id: 'storage-empty-garbage',
      name: 'Empty Garbage',
      description: 'Empty the garbage in storage.',
      taskType: TaskType.SHORT,
      roomId: 'storage',
      minigameType: MinigameType.EMPTY,
      isVisual: false,
    },
    {
      id: 'medbay-submit-scan',
      name: 'Submit Scan',
      description: 'Complete a medical scan to verify your identity.',
      taskType: TaskType.LONG,
      roomId: 'medbay',
      minigameType: MinigameType.SCAN,
      isVisual: true,
    },
    {
      id: 'security-fix-wiring',
      name: 'Fix Wiring',
      description: 'Repair the security camera wiring.',
      taskType: TaskType.SHORT,
      roomId: 'security',
      minigameType: MinigameType.WIRES,
      isVisual: false,
    },
    {
      id: 'reactor-start-reactor',
      name: 'Start Reactor',
      description: 'Start the main reactor by repeating the pattern.',
      taskType: TaskType.LONG,
      roomId: 'reactor',
      minigameType: MinigameType.SWIPE,
      isVisual: false,
    },
    {
      id: 'engine-align-engine',
      name: 'Align Engine',
      description: 'Align the main engine output.',
      taskType: TaskType.SHORT,
      roomId: 'engine',
      minigameType: MinigameType.SWIPE,
      isVisual: false,
    },
    {
      id: 'engine-fuel-engines',
      name: 'Fuel Engines',
      description: 'Refuel the main engines.',
      taskType: TaskType.LONG,
      roomId: 'engine',
      minigameType: MinigameType.FUEL,
      isVisual: false,
    },
    {
      id: 'lower-engine-align-engine',
      name: 'Align Engine',
      description: 'Align the lower engine output.',
      taskType: TaskType.SHORT,
      roomId: 'lower-engine',
      minigameType: MinigameType.SWIPE,
      isVisual: false,
    },
  ],
};

export function getTasksByRoom(roomId: string): TaskDefinition[] {
  return SKELD_TASKS.tasks.filter((task) => task.roomId === roomId);
}

export function getVisualTasks(): TaskDefinition[] {
  return SKELD_TASKS.tasks.filter((task) => task.isVisual);
}

export function getTasksByType(taskType: TaskType): TaskDefinition[] {
  return SKELD_TASKS.tasks.filter((task) => task.taskType === taskType);
}
